"""
Comprehensive World Recipe Database
120+ recipes from 15+ cuisines with 200+ unique ingredients
"""

def get_world_recipes():
    """Returns comprehensive recipe dataset"""
    return [
        # === ASIAN CUISINE (30 recipes) ===
        
        # Chinese
        {'id': 1, 'name': 'Kung Pao Chicken', 'cuisine': 'Chinese',
         'ingredients': ['chicken', 'peanuts', 'soy sauce', 'ginger', 'garlic', 'chili peppers', 'rice vinegar', 'cornstarch', 'scallions']},
        {'id': 2, 'name': 'Mapo Tofu', 'cuisine': 'Chinese',
         'ingredients': ['tofu', 'ground pork', 'soy sauce', 'fermented black beans', 'garlic', 'ginger', 'chili oil', 'scallions']},
        {'id': 3, 'name': 'Sweet and Sour Pork', 'cuisine': 'Chinese',
         'ingredients': ['pork', 'bell peppers', 'pineapple', 'rice vinegar', 'sugar', 'ketchup', 'soy sauce', 'cornstarch']},
        {'id': 4, 'name': 'Beef and Broccoli', 'cuisine': 'Chinese',
         'ingredients': ['beef', 'broccoli', 'soy sauce', 'oyster sauce', 'garlic', 'ginger', 'cornstarch', 'sesame oil']},
        {'id': 5, 'name': 'Egg Fried Rice', 'cuisine': 'Chinese',
         'ingredients': ['rice', 'eggs', 'peas', 'carrots', 'soy sauce', 'garlic', 'scallions', 'sesame oil']},
        
        # Thai
        {'id': 6, 'name': 'Pad Thai', 'cuisine': 'Thai',
         'ingredients': ['rice noodles', 'shrimp', 'eggs', 'peanuts', 'bean sprouts', 'fish sauce', 'tamarind', 'lime', 'garlic']},
        {'id': 7, 'name': 'Green Curry', 'cuisine': 'Thai',
         'ingredients': ['chicken', 'green curry paste', 'coconut milk', 'bamboo shoots', 'thai basil', 'fish sauce', 'palm sugar', 'lime']},
        {'id': 8, 'name': 'Tom Yum Soup', 'cuisine': 'Thai',
         'ingredients': ['shrimp', 'lemongrass', 'galangal', 'kaffir lime leaves', 'mushrooms', 'fish sauce', 'lime juice', 'chili peppers']},
        {'id': 9, 'name': 'Massaman Curry', 'cuisine': 'Thai',
         'ingredients': ['beef', 'massaman curry paste', 'coconut milk', 'potatoes', 'peanuts', 'fish sauce', 'tamarind', 'palm sugar']},
        {'id': 10, 'name': 'Pad See Ew', 'cuisine': 'Thai',
         'ingredients': ['wide rice noodles', 'chicken', 'chinese broccoli', 'eggs', 'soy sauce', 'oyster sauce', 'garlic', 'sugar']},
        
        # Japanese
        {'id': 11, 'name': 'Chicken Teriyaki', 'cuisine': 'Japanese',
         'ingredients': ['chicken thighs', 'soy sauce', 'mirin', 'sake', 'sugar', 'ginger', 'garlic', 'sesame seeds']},
        {'id': 12, 'name': 'Salmon Teriyaki', 'cuisine': 'Japanese',
         'ingredients': ['salmon', 'soy sauce', 'mirin', 'sake', 'sugar', 'ginger', 'sesame seeds']},
        {'id': 13, 'name': 'Ramen', 'cuisine': 'Japanese',
         'ingredients': ['ramen noodles', 'pork belly', 'soft boiled eggs', 'scallions', 'nori', 'soy sauce', 'miso', 'dashi']},
        {'id': 14, 'name': 'Vegetable Tempura', 'cuisine': 'Japanese',
         'ingredients': ['sweet potato', 'eggplant', 'zucchini', 'flour', 'eggs', 'ice water', 'soy sauce', 'dashi']},
        {'id': 15, 'name': 'Tonkatsu', 'cuisine': 'Japanese',
         'ingredients': ['pork cutlets', 'flour', 'eggs', 'panko breadcrumbs', 'cabbage', 'tonkatsu sauce']},
        
        # Korean
        {'id': 16, 'name': 'Bibimbap', 'cuisine': 'Korean',
         'ingredients': ['rice', 'beef', 'spinach', 'bean sprouts', 'carrots', 'mushrooms', 'eggs', 'gochujang', 'sesame oil']},
        {'id': 17, 'name': 'Bulgogi', 'cuisine': 'Korean',
         'ingredients': ['beef', 'soy sauce', 'sugar', 'sesame oil', 'garlic', 'ginger', 'pear', 'scallions']},
        {'id': 18, 'name': 'Kimchi Fried Rice', 'cuisine': 'Korean',
         'ingredients': ['rice', 'kimchi', 'pork', 'eggs', 'gochujang', 'sesame oil', 'scallions', 'garlic']},
        {'id': 19, 'name': 'Korean Fried Chicken', 'cuisine': 'Korean',
         'ingredients': ['chicken wings', 'flour', 'cornstarch', 'gochujang', 'honey', 'soy sauce', 'garlic', 'sesame seeds']},
        {'id': 20, 'name': 'Japchae', 'cuisine': 'Korean',
         'ingredients': ['sweet potato noodles', 'beef', 'spinach', 'mushrooms', 'carrots', 'soy sauce', 'sesame oil', 'sugar']},
        
        # Indian
        {'id': 21, 'name': 'Butter Chicken', 'cuisine': 'Indian',
         'ingredients': ['chicken', 'butter', 'cream', 'tomato sauce', 'garam masala', 'ginger', 'garlic', 'fenugreek']},
        {'id': 22, 'name': 'Chicken Tikka Masala', 'cuisine': 'Indian',
         'ingredients': ['chicken', 'yogurt', 'tomato sauce', 'cream', 'garam masala', 'turmeric', 'ginger', 'garlic', 'coriander']},
        {'id': 23, 'name': 'Palak Paneer', 'cuisine': 'Indian',
         'ingredients': ['paneer', 'spinach', 'cream', 'tomatoes', 'ginger', 'garlic', 'garam masala', 'cumin']},
        {'id': 24, 'name': 'Chana Masala', 'cuisine': 'Indian',
         'ingredients': ['chickpeas', 'tomatoes', 'onions', 'ginger', 'garlic', 'garam masala', 'cumin', 'coriander', 'turmeric']},
        {'id': 25, 'name': 'Lamb Rogan Josh', 'cuisine': 'Indian',
         'ingredients': ['lamb', 'yogurt', 'tomatoes', 'onions', 'ginger', 'garlic', 'garam masala', 'paprika', 'cardamom']},
        {'id': 26, 'name': 'Biryani', 'cuisine': 'Indian',
         'ingredients': ['basmati rice', 'chicken', 'yogurt', 'onions', 'garam masala', 'saffron', 'mint', 'cilantro']},
        {'id': 27, 'name': 'Dal Tadka', 'cuisine': 'Indian',
         'ingredients': ['lentils', 'tomatoes', 'onions', 'garlic', 'ginger', 'cumin', 'turmeric', 'ghee', 'cilantro']},
        {'id': 28, 'name': 'Samosas', 'cuisine': 'Indian',
         'ingredients': ['potatoes', 'peas', 'flour', 'cumin', 'coriander', 'garam masala', 'ginger', 'turmeric']},
        
        # Vietnamese
        {'id': 29, 'name': 'Pho', 'cuisine': 'Vietnamese',
         'ingredients': ['rice noodles', 'beef', 'beef broth', 'star anise', 'cinnamon', 'ginger', 'onions', 'basil', 'lime']},
        {'id': 30, 'name': 'Banh Mi', 'cuisine': 'Vietnamese',
         'ingredients': ['baguette', 'pork', 'pickled vegetables', 'cilantro', 'jalapen peppers', 'mayonnaise', 'soy sauce']},
        
        # === EUROPEAN CUISINE (30 recipes) ===
        
        # Italian
        {'id': 31, 'name': 'Spaghetti Carbonara', 'cuisine': 'Italian',
         'ingredients': ['spaghetti', 'guanciale', 'eggs', 'pecorino romano', 'black pepper']},
        {'id': 32, 'name': 'Lasagna', 'cuisine': 'Italian',
         'ingredients': ['lasagna noodles', 'ground beef', 'ricotta', 'mozzarella', 'parmesan', 'tomato sauce', 'onions', 'garlic']},
        {'id': 33, 'name': 'Margherita Pizza', 'cuisine': 'Italian',
         'ingredients': ['pizza dough', 'tomato sauce', 'mozzarella', 'basil', 'olive oil']},
        {'id': 34, 'name': 'Risotto alla Milanese', 'cuisine': 'Italian',
         'ingredients': ['arborio rice', 'saffron', 'white wine', 'parmesan', 'butter', 'onions', 'beef broth']},
        {'id': 35, 'name': 'Osso Buco', 'cuisine': 'Italian',
         'ingredients': ['veal shanks', 'white wine', 'tomatoes', 'carrots', 'celery', 'onions', 'garlic', 'parsley']},
        {'id': 36, 'name': 'Fettuccine Alfredo', 'cuisine': 'Italian',
         'ingredients': ['fettuccine', 'butter', 'parmesan', 'cream', 'garlic', 'black pepper']},
        {'id': 37, 'name': 'Penne Arrabbiata', 'cuisine': 'Italian',
         'ingredients': ['penne pasta', 'tomatoes', 'garlic', 'red chili flakes', 'olive oil', 'parsley']},
        {'id': 38, 'name': 'Caprese Salad', 'cuisine': 'Italian',
         'ingredients': ['tomatoes', 'mozzarella', 'basil', 'olive oil', 'balsamic vinegar']},
        
        # French
        {'id': 39, 'name': 'Coq au Vin', 'cuisine': 'French',
         'ingredients': ['chicken', 'red wine', 'bacon', 'mushrooms', 'onions', 'carrots', 'thyme', 'bay leaves']},
        {'id': 40, 'name': 'Beef Bourguignon', 'cuisine': 'French',
         'ingredients': ['beef chuck', 'red wine', 'bacon', 'mushrooms', 'pearl onions', 'carrots', 'thyme', 'bay leaves']},
        {'id': 41, 'name': 'Ratatouille', 'cuisine': 'French',
         'ingredients': ['eggplant', 'zucchini', 'tomatoes', 'bell peppers', 'onions', 'garlic', 'olive oil', 'thyme']},
        {'id': 42, 'name': 'Quiche Lorraine', 'cuisine': 'French',
         'ingredients': ['pie crust', 'bacon', 'eggs', 'cream', 'gruyere cheese', 'nutmeg']},
        {'id': 43, 'name': 'French Onion Soup', 'cuisine': 'French',
         'ingredients': ['onions', 'beef broth', 'white wine', 'gruyere cheese', 'baguette', 'butter', 'thyme']},
        {'id': 44, 'name': 'Crème Brûlée', 'cuisine': 'French',
         'ingredients': ['heavy cream', 'egg yolks', 'sugar', 'vanilla extract']},
        
        # Spanish
        {'id': 45, 'name': 'Paella', 'cuisine': 'Spanish',
         'ingredients': ['rice', 'chicken', 'shrimp', 'mussels', 'bell peppers', 'tomatoes', 'saffron', 'paprika', 'garlic']},
        {'id': 46, 'name': 'Gazpacho', 'cuisine': 'Spanish',
         'ingredients': ['tomatoes', 'cucumber', 'bell peppers', 'onions', 'garlic', 'olive oil', 'vinegar', 'bread']},
        {'id': 47, 'name': 'Tortilla Española', 'cuisine': 'Spanish',
         'ingredients': ['potatoes', 'eggs', 'onions', 'olive oil', 'salt']},
        {'id': 48, 'name': 'Patatas Bravas', 'cuisine': 'Spanish',
         'ingredients': ['potatoes', 'tomato sauce', 'paprika', 'garlic', 'olive oil', 'mayonnaise']},
        
        # Greek
        {'id': 49, 'name': 'Moussaka', 'cuisine': 'Greek',
         'ingredients': ['eggplant', 'ground lamb', 'potatoes', 'béchamel sauce', 'tomatoes', 'onions', 'cinnamon']},
        {'id': 50, 'name': 'Greek Salad', 'cuisine': 'Greek',
         'ingredients': ['tomatoes', 'cucumber', 'red onions', 'feta cheese', 'olives', 'olive oil', 'oregano']},
        {'id': 51, 'name': 'Souvlaki', 'cuisine': 'Greek',
         'ingredients': ['pork', 'lemon juice', 'olive oil', 'garlic', 'oregano', 'pita bread', 'tzatziki']},
        {'id': 52, 'name': 'Spanakopita', 'cuisine': 'Greek',
         'ingredients': ['spinach', 'feta cheese', 'phyllo dough', 'eggs', 'onions', 'dill', 'olive oil']},
        
        # German
        {'id': 53, 'name': 'Schnitzel', 'cuisine': 'German',
         'ingredients': ['pork cutlets', 'flour', 'eggs', 'breadcrumbs', 'lemon', 'butter']},
        {'id': 54, 'name': 'Bratwurst', 'cuisine': 'German',
         'ingredients': ['pork sausages', 'sauerkraut', 'onions', 'mustard', 'beer']},
        {'id': 55, 'name': 'Sauerbraten', 'cuisine': 'German',
         'ingredients': ['beef roast', 'red wine vinegar', 'onions', 'carrots', 'gingersnaps', 'red wine']},
        
        # British
        {'id': 56, 'name': 'Fish and Chips', 'cuisine': 'British',
         'ingredients': ['cod', 'potatoes', 'flour', 'beer', 'baking powder', 'malt vinegar']},
        {'id': 57, 'name': 'Shepherd\'s Pie', 'cuisine': 'British',
         'ingredients': ['ground lamb', 'potatoes', 'carrots', 'peas', 'onions', 'beef broth', 'worcestershire sauce']},
        {'id': 58, 'name': 'Beef Wellington', 'cuisine': 'British',
         'ingredients': ['beef tenderloin', 'puff pastry', 'mushrooms', 'pâté', 'prosciutto', 'egg wash']},
        {'id': 59, 'name': 'Bangers and Mash', 'cuisine': 'British',
         'ingredients': ['pork sausages', 'potatoes', 'onions', 'butter', 'milk', 'gravy']},
        {'id': 60, 'name': 'Chicken Tikka Pizza', 'cuisine': 'British-Indian',
         'ingredients': ['pizza dough', 'chicken tikka', 'mozzarella', 'red onions', 'cilantro', 'mango chutney']},
        
        # === AMERICAN CUISINE (20 recipes) ===
        
        {'id': 61, 'name': 'Classic Burger', 'cuisine': 'American',
         'ingredients': ['ground beef', 'burger buns', 'lettuce', 'tomatoes', 'onions', 'pickles', 'cheese', 'ketchup', 'mustard']},
        {'id': 62, 'name': 'Buffalo Wings', 'cuisine': 'American',
         'ingredients': ['chicken wings', 'hot sauce', 'butter', 'vinegar', 'garlic powder', 'blue cheese dressing', 'celery']},
        {'id': 63, 'name': 'BBQ Ribs', 'cuisine': 'American',
         'ingredients': ['pork ribs', 'bbq sauce', 'brown sugar', 'paprika', 'garlic powder', 'onion powder', 'black pepper']},
        {'id': 64, 'name': 'Mac and Cheese', 'cuisine': 'American',
         'ingredients': ['macaroni', 'cheddar cheese', 'milk', 'butter', 'flour', 'breadcrumbs']},
        {'id': 65, 'name': 'Fried Chicken', 'cuisine': 'American',
         'ingredients': ['chicken pieces', 'buttermilk', 'flour', 'paprika', 'garlic powder', 'cayenne pepper', 'salt']},
        {'id': 66, 'name': 'Caesar Salad', 'cuisine': 'American',
         'ingredients': ['romaine lettuce', 'croutons', 'parmesan', 'caesar dressing', 'anchovies', 'lemon', 'garlic']},
        {'id': 67, 'name': 'Cobb Salad', 'cuisine': 'American',
         'ingredients': ['lettuce', 'chicken', 'bacon', 'eggs', 'avocado', 'tomatoes', 'blue cheese', 'ranch dressing']},
        {'id': 68, 'name': 'Pulled Pork Sandwich', 'cuisine': 'American',
         'ingredients': ['pork shoulder', 'bbq sauce', 'coleslaw', 'burger buns', 'apple cider vinegar', 'brown sugar']},
        {'id': 69, 'name': 'Jambalaya', 'cuisine': 'Cajun',
         'ingredients': ['rice', 'chicken', 'andouille sausage', 'shrimp', 'bell peppers', 'celery', 'onions', 'cajun seasoning']},
        {'id': 70, 'name': 'Gumbo', 'cuisine': 'Cajun',
         'ingredients': ['chicken', 'andouille sausage', 'okra', 'bell peppers', 'celery', 'onions', 'file powder', 'rice']},
        {'id': 71, 'name': 'Clam Chowder', 'cuisine': 'American',
         'ingredients': ['clams', 'potatoes', 'bacon', 'onions', 'celery', 'cream', 'butter', 'thyme']},
        {'id': 72, 'name': 'Chili Con Carne', 'cuisine': 'Tex-Mex',
         'ingredients': ['ground beef', 'kidney beans', 'tomatoes', 'onions', 'chili powder', 'cumin', 'garlic']},
        {'id': 73, 'name': 'Fajitas', 'cuisine': 'Tex-Mex',
         'ingredients': ['chicken', 'bell peppers', 'onions', 'tortillas', 'lime', 'cumin', 'chili powder', 'sour cream']},
        {'id': 74, 'name': 'Quesadillas', 'cuisine': 'Mexican',
         'ingredients': ['tortillas', 'cheese', 'chicken', 'bell peppers', 'onions', 'sour cream', 'salsa']},
        {'id': 75, 'name': 'Enchiladas', 'cuisine': 'Mexican',
         'ingredients': ['tortillas', 'chicken', 'cheese', 'enchilada sauce', 'onions', 'sour cream', 'cilantro']},
        {'id': 76, 'name': 'Tacos al Pastor', 'cuisine': 'Mexican',
         'ingredients': ['pork', 'pineapple', 'onions', 'cilantro', 'lime', 'tortillas', 'chili peppers']},
        {'id': 77, 'name': 'Carnitas', 'cuisine': 'Mexican',
         'ingredients': ['pork shoulder', 'orange juice', 'lime', 'cumin', 'oregano', 'garlic', 'onions']},
        {'id': 78, 'name': 'Guacamole', 'cuisine': 'Mexican',
         'ingredients': ['avocados', 'lime', 'cilantro', 'onions', 'tomatoes', 'jalapeño peppers', 'salt']},
        {'id': 79, 'name': 'Nachos', 'cuisine': 'Tex-Mex',
         'ingredients': ['tortilla chips', 'cheese', 'ground beef', 'jalapeños', 'sour cream', 'salsa', 'guacamole']},
        {'id': 80, 'name': 'Burrito Bowl', 'cuisine': 'Tex-Mex',
         'ingredients': ['rice', 'black beans', 'chicken', 'cheese', 'salsa', 'guacamole', 'sour cream', 'lettuce']},
        
        # === MIDDLE EASTERN & AFRICAN CUISINE (15 recipes) ===
        
        {'id': 81, 'name': 'Falafel', 'cuisine': 'Middle Eastern',
         'ingredients': ['chickpeas', 'parsley', 'cilantro', 'onions', 'garlic', 'cumin', 'coriander', 'flour']},
        {'id': 82, 'name': 'Hummus', 'cuisine': 'Middle Eastern',
         'ingredients': ['chickpeas', 'tahini', 'lemon juice', 'garlic', 'olive oil', 'cumin']},
        {'id': 83, 'name': 'Shawarma', 'cuisine': 'Middle Eastern',
         'ingredients': ['chicken', 'yogurt', 'lemon', 'garlic', 'cumin', 'paprika', 'pita bread', 'tahini']},
        {'id': 84, 'name': 'Tabbouleh', 'cuisine': 'Middle Eastern',
         'ingredients': ['bulgur', 'parsley', 'tomatoes', 'cucumber', 'mint', 'lemon juice', 'olive oil']},
        {'id': 85, 'name': 'Baba Ganoush', 'cuisine': 'Middle Eastern',
         'ingredients': ['eggplant', 'tahini', 'lemon juice', 'garlic', 'olive oil', 'cumin']},
        {'id': 86, 'name': 'Kebabs', 'cuisine': 'Middle Eastern',
         'ingredients': ['lamb', 'onions', 'bell peppers', 'tomatoes', 'cumin', 'paprika', 'yogurt']},
        {'id': 87, 'name': 'Mansaf', 'cuisine': 'Middle Eastern',
         'ingredients': ['lamb', 'rice', 'yogurt', 'jameed', 'pine nuts', 'almonds']},
        {'id': 88, 'name': 'Shakshuka', 'cuisine': 'Middle Eastern',
         'ingredients': ['eggs', 'tomatoes', 'bell peppers', 'onions', 'garlic', 'cumin', 'paprika', 'feta cheese']},
        {'id': 89, 'name': 'Koshari', 'cuisine': 'Egyptian',
         'ingredients': ['rice', 'lentils', 'pasta', 'chickpeas', 'tomato sauce', 'onions', 'cumin']},
        {'id': 90, 'name': 'Tagine', 'cuisine': 'Moroccan',
         'ingredients': ['chicken', 'preserved lemons', 'olives', 'onions', 'ginger', 'saffron', 'cinnamon', 'cumin']},
        {'id': 91, 'name': 'Couscous', 'cuisine': 'North African',
         'ingredients': ['couscous', 'chickpeas', 'carrots', 'zucchini', 'onions', 'raisins', 'cinnamon', 'cumin']},
        {'id': 92, 'name': 'Jollof Rice', 'cuisine': 'West African',
         'ingredients': ['rice', 'tomatoes', 'tomato paste', 'onions', 'bell peppers', 'thyme', 'curry powder', 'chicken']},
        {'id': 93, 'name': 'Suya', 'cuisine': 'Nigerian',
         'ingredients': ['beef', 'peanuts', 'ginger', 'garlic', 'paprika', 'cayenne pepper', 'onion powder']},
        {'id': 94, 'name': 'Peri Peri Chicken', 'cuisine': 'African',
         'ingredients': ['chicken', 'peri peri peppers', 'lemon', 'garlic', 'paprika', 'olive oil']},
        {'id': 95, 'name': 'Bobotie', 'cuisine': 'South African',
         'ingredients': ['ground beef', 'curry powder', 'raisins', 'almonds', 'eggs', 'milk', 'bread', 'turmeric']},
        
        # === VEGETARIAN & VEGAN (15 recipes) ===
        
        {'id': 96, 'name': 'Vegetable Stir Fry', 'cuisine': 'Asian',
         'ingredients': ['tofu', 'broccoli', 'bell peppers', 'carrots', 'soy sauce', 'ginger', 'garlic', 'sesame oil']},
        {'id': 97, 'name': 'Lentil Soup', 'cuisine': 'Mediterranean',
         'ingredients': ['lentils', 'carrots', 'celery', 'onions', 'tomatoes', 'garlic', 'cumin', 'vegetable broth']},
        {'id': 98, 'name': 'Vegetable Lasagna', 'cuisine': 'Italian',
         'ingredients': ['lasagna noodles', 'zucchini', 'mushrooms', 'spinach', 'ricotta', 'mozzarella', 'tomato sauce']},
        {'id': 99, 'name': 'Buddha Bowl', 'cuisine': 'Fusion',
         'ingredients': ['quinoa', 'chickpeas', 'kale', 'sweet potato', 'avocado', 'tahini', 'lemon']},
        {'id': 100, 'name': 'Vegan Burrito', 'cuisine': 'Mexican',
         'ingredients': ['tortilla', 'black beans', 'rice', 'guacamole', 'salsa', 'lettuce', 'vegan cheese']},
        {'id': 101, 'name': 'Mushroom Stroganoff', 'cuisine': 'Russian',
         'ingredients': ['mushrooms', 'onions', 'garlic', 'sour cream', 'flour', 'vegetable broth', 'egg noodles']},
        {'id': 102, 'name': 'Eggplant Parmesan', 'cuisine': 'Italian',
         'ingredients': ['eggplant', 'mozzarella', 'parmesan', 'tomato sauce', 'basil', 'breadcrumbs', 'eggs']},
        {'id': 103, 'name': 'Tofu Scramble', 'cuisine': 'Vegan',
         'ingredients': ['tofu', 'turmeric', 'nutritional yeast', 'onions', 'bell peppers', 'spinach', 'garlic']},
        {'id': 104, 'name': 'Cauliflower Tacos', 'cuisine': 'Mexican',
         'ingredients': ['cauliflower', 'tortillas', 'avocado', 'cabbage', 'lime', 'cumin', 'paprika']},
        {'id': 105, 'name': 'Vegan Pad Thai', 'cuisine': 'Thai',
         'ingredients': ['rice noodles', 'tofu', 'peanuts', 'bean sprouts', 'tamarind', 'lime', 'soy sauce']},
        {'id': 106, 'name': 'Portobello Mushroom Burger', 'cuisine': 'American',
         'ingredients': ['portobello mushrooms', 'burger buns', 'lettuce', 'tomatoes', 'onions', 'balsamic vinegar']},
        {'id': 107, 'name': 'Chickpea Curry', 'cuisine': 'Indian',
         'ingredients': ['chickpeas', 'coconut milk', 'tomatoes', 'onions', 'curry powder', 'ginger', 'garlic']},
        {'id': 108, 'name': 'Stuffed Bell Peppers', 'cuisine': 'Mediterranean',
         'ingredients': ['bell peppers', 'rice', 'black beans', 'corn', 'tomatoes', 'cheese', 'cumin']},
        {'id': 109, 'name': 'Vegan Sushi Bowl', 'cuisine': 'Japanese',
         'ingredients': ['sushi rice', 'avocado', 'cucumber', 'carrots', 'edamame', 'nori', 'soy sauce', 'sesame seeds']},
        {'id': 110, 'name': 'Minestrone Soup', 'cuisine': 'Italian',
         'ingredients': ['pasta', 'kidney beans', 'tomatoes', 'zucchini', 'carrots', 'celery', 'onions', 'basil']},
        
        # === FUSION & MODERN (10 recipes) ===
        
        {'id': 111, 'name': 'Korean BBQ Tacos', 'cuisine': 'Fusion',
         'ingredients': ['beef bulgogi', 'tortillas', 'kimchi', 'gochujang', 'sesame seeds', 'scallions']},
        {'id': 112, 'name': 'Sushi Burrito', 'cuisine': 'Fusion',
         'ingredients': ['sushi rice', 'nori', 'salmon', 'avocado', 'cucumber', 'spicy mayo', 'sesame seeds']},
        {'id': 113, 'name': 'Ramen Burger', 'cuisine': 'Fusion',
         'ingredients': ['ramen noodles', 'ground beef', 'eggs', 'lettuce', 'teriyaki sauce', 'sesame seeds']},
        {'id': 114, 'name': 'Butter Chicken Pizza', 'cuisine': 'Fusion',
         'ingredients': ['pizza dough', 'butter chicken', 'mozzarella', 'red onions', 'cilantro', 'naan crumbs']},
        {'id': 115, 'name': 'Thai Basil Pasta', 'cuisine': 'Fusion',
         'ingredients': ['spaghetti', 'chicken', 'thai basil', 'fish sauce', 'chili peppers', 'garlic', 'soy sauce']},
        {'id': 116, 'name': 'Kimchi Quesadilla', 'cuisine': 'Fusion',
         'ingredients': ['tortillas', 'kimchi', 'cheese', 'pork', 'scallions', 'gochujang mayo']},
        {'id': 117, 'name': 'Miso Glazed Salmon', 'cuisine': 'Fusion',
         'ingredients': ['salmon', 'miso paste', 'mirin', 'sake', 'brown sugar', 'ginger']},
        {'id': 118, 'name': 'Poke Bowl', 'cuisine': 'Hawaiian',
         'ingredients': ['sushi rice', 'tuna', 'avocado', 'edamame', 'cucumber', 'soy sauce', 'sesame oil', 'seaweed']},
        {'id': 119, 'name': 'Açai Bowl', 'cuisine': 'Brazilian',
         'ingredients': ['açai', 'banana', 'granola', 'strawberries', 'blueberries', 'honey', 'coconut flakes']},
        {'id': 120, 'name': 'Shakshuka Pizza', 'cuisine': 'Fusion',
         'ingredients': ['pizza dough', 'tomato sauce', 'eggs', 'feta cheese', 'bell peppers', 'cumin', 'paprika']},
    ]


def get_ingredient_categories():
    """Returns comprehensive ingredient category mapping"""
    return {
        # Proteins - Meat
        'chicken': 'protein_meat',
        'chicken thighs': 'protein_meat',
        'chicken wings': 'protein_meat',
        'chicken pieces': 'protein_meat',
        'beef': 'protein_meat',
        'ground beef': 'protein_meat',
        'beef chuck': 'protein_meat',
        'beef roast': 'protein_meat',
        'beef tenderloin': 'protein_meat',
        'beef bulgogi': 'protein_meat',
        'pork': 'protein_meat',
        'pork shoulder': 'protein_meat',
        'pork belly': 'protein_meat',
        'pork cutlets': 'protein_meat',
        'pork ribs': 'protein_meat',
        'ground pork': 'protein_meat',
        'bacon': 'protein_meat',
        'guanciale': 'protein_meat',
        'prosciutto': 'protein_meat',
        'lamb': 'protein_meat',
        'ground lamb': 'protein_meat',
        'veal shanks': 'protein_meat',
        
        # Proteins - Poultry
        'duck': 'protein_poultry',
        'turkey': 'protein_poultry',
        
        # Proteins - Seafood
        'shrimp': 'protein_seafood',
        'fish': 'protein_seafood',
        'salmon': 'protein_seafood',
        'tuna': 'protein_seafood',
        'cod': 'protein_seafood',
        'clams': 'protein_seafood',
        'mussels': 'protein_seafood',
        'anchovies': 'protein_seafood',
        
        # Proteins - Plant-based
        'tofu': 'protein_plant',
        'tempeh': 'protein_plant',
        'seitan': 'protein_plant',
        'lentils': 'protein_legume',
        'chickpeas': 'protein_legume',
        'black beans': 'protein_legume',
        'kidney beans': 'protein_legume',
        'peas': 'protein_legume',
        
        # Proteins - Eggs & Dairy Proteins
        'eggs': 'protein_egg',
        'egg yolks': 'protein_egg',
        'soft boiled eggs': 'protein_egg',
        'flax eggs': 'protein_egg_substitute',
        'paneer': 'dairy_cheese',
        
        # Dairy
        'milk': 'dairy',
        'cream': 'dairy',
        'heavy cream': 'dairy',
        'sour cream': 'dairy',
        'yogurt': 'dairy',
        'butter': 'dairy',
        'ghee': 'dairy',
        'buttermilk': 'dairy',
        'cheese': 'dairy_cheese',
        'mozzarella': 'dairy_cheese',
        'parmesan': 'dairy_cheese',
        'cheddar cheese': 'dairy_cheese',
        'feta cheese': 'dairy_cheese',
        'blue cheese': 'dairy_cheese',
        'gruyere cheese': 'dairy_cheese',
        'pecorino romano': 'dairy_cheese',
        'ricotta': 'dairy_cheese',
        
        # Dairy Substitutes
        'almond milk': 'dairy_substitute',
        'coconut milk': 'dairy_substitute',
        'vegan cheese': 'dairy_substitute',
        'coconut oil': 'oil',
        'nutritional yeast': 'dairy_substitute',
        
        # Grains - Pasta
        'pasta': 'grain_pasta',
        'spaghetti': 'grain_pasta',
        'fettuccine': 'grain_pasta',
        'penne pasta': 'grain_pasta',
        'lasagna noodles': 'grain_pasta',
        'macaroni': 'grain_pasta',
        'egg noodles': 'grain_pasta',
        
        # Grains - Noodles
        'rice noodles': 'grain_noodles',
        'ramen noodles': 'grain_noodles',
        'wide rice noodles': 'grain_noodles',
        'sweet potato noodles': 'grain_noodles',
        
        # Grains - Rice
        'rice': 'grain_rice',
        'arborio rice': 'grain_rice',
        'basmati rice': 'grain_rice',
        'sushi rice': 'grain_rice',
        'brown rice': 'grain_rice',
        
        # Grains - Other
        'flour': 'grain_flour',
        'bread': 'grain_bread',
        'baguette': 'grain_bread',
        'pita bread': 'grain_bread',
        'naan': 'grain_bread',
        'burger buns': 'grain_bread',
        'tortillas': 'grain_wrap',
        'tortilla chips': 'grain_chips',
        'dough': 'grain_dough',
        'pizza dough': 'grain_dough',
        'pie crust': 'grain_dough',
        'puff pastry': 'grain_dough',
        'phyllo dough': 'grain_dough',
        'quinoa': 'grain_other',
        'couscous': 'grain_other',
        'bulgur': 'grain_other',
        'breadcrumbs': 'grain_other',
        'panko breadcrumbs': 'grain_other',
        'croutons': 'grain_other',
        'cornstarch': 'grain_starch',
        'baking powder': 'baking',
        
        # Vegetables
        'vegetables': 'vegetable',
        'broccoli': 'vegetable',
        'chinese broccoli': 'vegetable',
        'spinach': 'vegetable',
        'kale': 'vegetable',
        'lettuce': 'vegetable',
        'romaine lettuce': 'vegetable',
        'cabbage': 'vegetable',
        'tomatoes': 'vegetable',
        'bell peppers': 'vegetable',
        'chili peppers': 'vegetable',
        'jalapeño peppers': 'vegetable',
        'peri peri peppers': 'vegetable',
        'onions': 'vegetable',
        'red onions': 'vegetable',
        'pearl onions': 'vegetable',
        'scallions': 'vegetable',
        'garlic': 'aromatics',
        'ginger': 'aromatics',
        'carrots': 'vegetable',
        'cucumber': 'vegetable',
        'celery': 'vegetable',
        'mushrooms': 'vegetable',
        'portobello mushrooms': 'vegetable',
        'eggplant': 'vegetable',
        'zucchini': 'vegetable',
        'potatoes': 'vegetable',
        'sweet potato': 'vegetable',
        'cauliflower': 'vegetable',
        'corn': 'vegetable',
        'okra': 'vegetable',
        'bamboo shoots': 'vegetable',
        'bean sprouts': 'vegetable',
        'edamame': 'vegetable',
        'avocado': 'fruit',
        'olives': 'fruit',
        
        # Fruits
        'lemon': 'citrus',
        'lemon juice': 'citrus',
        'lime': 'citrus',
        'lime juice': 'citrus',
        'orange juice': 'citrus',
        'pineapple': 'fruit',
        'banana': 'fruit',
        'strawberries': 'fruit',
        'blueberries': 'fruit',
        'raisins': 'fruit',
        'preserved lemons': 'citrus',
        
        # Sauces & Condiments
        'soy sauce': 'sauce_salty',
        'fish sauce': 'sauce_salty',
        'oyster sauce': 'sauce_salty',
        'worcestershire sauce': 'sauce_salty',
        'tonkatsu sauce': 'sauce_sweet',
        'teriyaki sauce': 'sauce_sweet',
        'tomato sauce': 'sauce_tomato',
        'tomato paste': 'sauce_tomato',
        'enchilada sauce': 'sauce_tomato',
        'salsa': 'sauce_tomato',
        'bbq sauce': 'sauce_sweet',
        'hot sauce': 'sauce_spicy',
        'gochujang': 'sauce_spicy',
        'chili oil': 'sauce_spicy',
        'tahini': 'sauce_seed',
        'peanut butter': 'sauce_nut',
        'ketchup': 'sauce_tomato',
        'mustard': 'condiment',
        'mayonnaise': 'condiment',
        'spicy mayo': 'condiment',
        'vinegar': 'acid',
        'rice vinegar': 'acid',
        'balsamic vinegar': 'acid',
        'malt vinegar': 'acid',
        'apple cider vinegar': 'acid',
        
        # Oils & Fats
        'oil': 'oil',
        'olive oil': 'oil',
        'sesame oil': 'oil',
        
        # Herbs & Spices
        'herbs': 'herbs',
        'basil': 'herbs',
        'thai basil': 'herbs',
        'cilantro': 'herbs',
        'parsley': 'herbs',
        'mint': 'herbs',
        'thyme': 'herbs',
        'oregano': 'herbs',
        'dill': 'herbs',
        'bay leaves': 'herbs',
        'nori': 'herbs',
        'seaweed': 'herbs',
        'lemongrass': 'aromatics',
        'kaffir lime leaves': 'aromatics',
        'galangal': 'aromatics',
        'star anise': 'spice',
        'cinnamon': 'spice',
        'black pepper': 'spice',
        'red chili flakes': 'spice',
        'paprika': 'spice',
        'cayenne pepper': 'spice',
        'curry powder': 'spice',
        'garam masala': 'spice',
        'cumin': 'spice',
        'coriander': 'spice',
        'turmeric': 'spice',
        'cardamom': 'spice',
        'saffron': 'spice',
        'nutmeg': 'spice',
        'garlic powder': 'spice',
        'onion powder': 'spice',
        'fenugreek': 'spice',
        'file powder': 'spice',
        'cajun seasoning': 'spice',
        'chili powder': 'spice',
        
        # Nuts & Seeds
        'peanuts': 'nuts',
        'almonds': 'nuts',
        'pine nuts': 'nuts',
        'sesame seeds': 'seeds',
        
        # Sweeteners
        'sugar': 'sweetener',
        'brown sugar': 'sweetener',
        'honey': 'sweetener',
        'palm sugar': 'sweetener',
        
        # Alcoholic
        'wine': 'alcohol',
        'red wine': 'alcohol',
        'white wine': 'alcohol',
        'sake': 'alcohol',
        'mirin': 'alcohol',
        'beer': 'alcohol',
        
        # Broths & Stocks
        'beef broth': 'broth',
        'vegetable broth': 'broth',
        'chicken broth': 'broth',
        'dashi': 'broth',
        
        # Specialty
        'miso': 'fermented',
        'miso paste': 'fermented',
        'fermented black beans': 'fermented',
        'kimchi': 'fermented',
        'sauerkraut': 'fermented',
        'pickled vegetables': 'pickled',
        'pickles': 'pickled',
        'tamarind': 'fruit',
        'cocoa powder': 'baking',
        'vanilla extract': 'baking',
        'pâté': 'meat_product',
        'sausages': 'meat_product',
        'pork sausages': 'meat_product',
        'andouille sausage': 'meat_product',
        'béchamel sauce': 'sauce_cream',
        'gravy': 'sauce_savory',
        'dressing': 'sauce_dressing',
        'caesar dressing': 'sauce_dressing',
        'ranch dressing': 'sauce_dressing',
        'blue cheese dressing': 'sauce_dressing',
        'tzatziki': 'sauce_yogurt',
        'green curry paste': 'curry_paste',
        'massaman curry paste': 'curry_paste',
        'jameed': 'dairy',
        'açai': 'fruit',
        'granola': 'grain_other',
        'coconut flakes': 'nuts',
        'mango chutney': 'condiment',
        'egg wash': 'protein_egg',
        'pear': 'fruit',
    }


if __name__ == '__main__':
    recipes = get_world_recipes()
    categories = get_ingredient_categories()
    
    print(f"Total recipes: {len(recipes)}")
    print(f"Total ingredient categories: {len(categories)}")
    print(f"\nSample recipe: {recipes[0]}")
    print(f"\nSample categories: {list(categories.items())[:5]}")
